
export default {
    "Bulgarian": "bg",
    "Catalan": "ca",
    "Czech": "cs",
    "Danish": "da",
    "Danish (Denmark)": "da-DK",
    "Dutch": "nl",
    "English": "en",
    "English (Australia)": "en-AU",
    "English (United Kingdom)": "en-GB",
    "English (India)": "en-IN",
    "English (New Zealand)": "en-NZ",
    "English (United States)": "en-US",
    "Estonian": "et",
    "Finnish": "fi",
    "Flemish": "nl-BE",
    "French": "fr",
    "French (Canada)": "fr-CA",
    "German": "de",
    "German (Switzerland)": "de-CH",
    "Greek": "el",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Indonesian": "id",
    "Italian": "it",
    "Japanese": "ja",
    "Korean": "ko",
    "Korean (South Korea)": "ko-KR",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Malay": "ms",
    "Norwegian": "no",
    "Polish": "pl",
    "Portuguese": "pt",
    "Portuguese (Brazil)": "pt-BR",
    "Portuguese (Portugal)": "pt-PT",
    "Romanian": "ro",
    "Russian": "ru",
    "Slovak": "sk",
    "Spanish": "es",
    "Spanish (Latin America)": "es-419",
    "Swedish": "sv",
    "Swedish (Sweden)": "sv-SE",
    "Turkish": "tr",
    "Ukrainian": "uk",
    "Vietnamese": "vi"
};